controller_manager:
  ros__parameters:
    update_rate: 100  # Matches the UR Gazebo simulation rate

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    robotiq_gripper_controller:
      type: position_controllers/GripperActionController

# The UR10 Arm Controller
joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false

# The Robotiq 2F-85 Gripper Controller
robotiq_gripper_controller:
  ros__parameters:
    default_root_joint: robotiq_85_left_knuckle_joint
    joint: robotiq_85_left_knuckle_joint
